[project]
name = "rag-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio==5.23.0",
    "pydantic>=2.10.6",
    "vllm==0.8.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
